### ISSUE TITLE
Pretty hydras not getting a big enough posframe

### ISSUE THREAD

**Issue by neh** [jerrypnz/major-mode-hydra.el#30] opened 2019-07-18 19:03 UTC
I'm having a strange issue with pretty hydras when using hydra-posframe. I'm not even sure this will be the right place to ask, but here we go anyway. I'm happy to help troubleshoot or resolve this any way I can; I'm still getting a handle on debugging elisp.

When showing a pretty hydra in a posframe, the frame will be sized two lines smaller than it should be, so it won't show the last line of the hydra or the blank line after it:

![pretty-hydra-too-small](https://user-images.githubusercontent.com/1794/61483788-65181400-a952-11e9-8e3b-fcd5ab1a5c38.png)

 If I put a `:min-height` on the posframe, the content will all be there:

![pretty-hydra-min-height](https://user-images.githubusercontent.com/1794/61483818-706b3f80-a952-11e9-80c3-6178367d2c6c.png)

And if I use the `lv` hydra display type, it will show all the content, although it looks like it's not getting an extra blank line at the bottom (assuming it's supposed to):

![pretty-hydra-lv](https://user-images.githubusercontent.com/1794/61483831-74975d00-a952-11e9-867b-4e39b67432df.png)

That hydra definition looks like this:

```  
(major-mode-hydra-define emacs-lisp-mode
    (:color amaranth :quit-key ("q" "<escape>"))
    ("Eval"
     (("b" eval-buffer "buffer" :exit t)
      ("e" eval-defun "defun")
      ("r" eval-region "region"))
     "REPL"
     (("I" ielm "ielm"))
     "Doc"
     (("d" describe-foo-at-point "thing-at-pt")
      ("f" describe-function "function")
      ("v" describe-variable "variable"))))
```

Any ideas on this? Thanks in advance for any help you can give, and thanks for a really useful package.

**Comment by jerrypnz** [comment] 2019-07-18 20:38
Ha you ran into the exact same issue I had. I initially thought it's a bug in pretty-hydra but as you mentioned, there is no problem when using `lv` display type (the extra new line at the end is also displayed as your screenshot shows). I was able to reproduce the issue with a simple `posframe-show` call.

```elisp
(posframe-show "*test-posframe*" :string "\n foo \n bar \n foobar \n" :internal-border-width 1 :internal-border-color "red")
```

and I saw two problems:

- Not all content is displayed when there are leading/trailing spaces on each line (which is the case for pretty hydra hints)
- No matter how many new lines I put at the end, it didn't affect the height at all

It seems to be an issue in `fit-frame-to-buffer` which posframe uses to resize the frame.

I got around it by forking `hydra-posframe` and adding an ugly hack: https://github.com/jerrypnz/hydra-posframe/commit/7a0506b0a6b75418d0c9c8927e022c2061b8881b

**Comment by neh** [comment] 2019-07-19 03:20
Glad to know it's not just me. I was finding it messy to use the hydra-posframe package, and it turns out not to be necessary any more anyway, so I removed it and adapted your workaround (eg. pasted it with one small modification) into `hydra-posframe-show` in the hydra package and that's working ok. It's unfortunately slow (I can see it adjust the frame size) and of course, it's a messy hack ;-). Is there a path to a real fix here? Is it a matter of digging through `fit-frame-to-buffer` to try and sort it out?

**Comment by jerrypnz** [comment] 2019-07-19 04:02
For me it feels fast enough and I never saw it adjust the size. I didn't get a chance to further dig into it but might be worth reproducing the issue with a minimal config and report a bug for posframe?

**Comment by jerrypnz** [comment] 2019-08-19 00:47
Closing it as it's not really an issue of pretty-hydra.

**Closed as completed by jerrypnz** 2019-08-19 00:47 UTC
